"""Base handlers — abstract interfaces.

Pattern from trycua/cua computer-server/handlers/base.py:
BaseAutomationHandler, BaseAccessibilityHandler, BaseFileHandler.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional


class BaseAutomationHandler(ABC):
    """Mouse, keyboard, clipboard, shell, window/process management."""

    @abstractmethod
    def is_desktop_locked(self) -> bool:
        """Check if Windows desktop is locked (Ctrl+Alt+Del screen)."""
        ...

    @abstractmethod
    async def screenshot(self) -> Dict[str, Any]:
        """Capture full desktop screenshot, return base64 PNG data."""
        ...

    @abstractmethod
    async def get_screen_size(self) -> Dict[str, int]:
        """Return {'width': W, 'height': H} for primary monitor."""
        ...

    @abstractmethod
    async def get_cursor_position(self) -> Dict[str, int]:
        """Return {'x': X, 'y': Y} cursor position."""
        ...

    @abstractmethod
    async def mouse_down(self, x=None, y=None, button="left") -> Dict[str, Any]: ...
    @abstractmethod
    async def mouse_up(self, x=None, y=None, button="left") -> Dict[str, Any]: ...
    @abstractmethod
    async def left_click(self, x=None, y=None) -> Dict[str, Any]: ...
    @abstractmethod
    async def right_click(self, x=None, y=None) -> Dict[str, Any]: ...
    @abstractmethod
    async def middle_click(self, x=None, y=None) -> Dict[str, Any]: ...
    @abstractmethod
    async def double_click(self, x=None, y=None) -> Dict[str, Any]: ...
    @abstractmethod
    async def move_cursor(self, x: int, y: int) -> Dict[str, Any]: ...
    @abstractmethod
    async def drag_to(self, x: int, y: int, button="left", duration=0.5) -> Dict[str, Any]: ...
    @abstractmethod
    async def scroll(self, scroll_x: int, scroll_y: int) -> Dict[str, Any]: ...

    @abstractmethod
    async def key_down(self, key: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def key_up(self, key: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def type_text(self, text: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def press_key(self, key: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def hotkey(self, keys: List[str]) -> Dict[str, Any]: ...

    @abstractmethod
    async def copy_to_clipboard(self) -> Dict[str, Any]: ...
    @abstractmethod
    async def set_clipboard(self, text: str) -> Dict[str, Any]: ...

    @abstractmethod
    async def run_command(self, command: str) -> Dict[str, Any]: ...

    @abstractmethod
    async def launch(self, app: str, args: List[str] | None = None) -> Dict[str, Any]: ...

    @abstractmethod
    async def get_current_window_id(self) -> Dict[str, Any]: ...
    @abstractmethod
    async def get_application_windows(self, app: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def list_all_windows(self) -> Dict[str, Any]: ...
    @abstractmethod
    async def resize_window(self, window_id: int, w: int, h: int) -> Dict[str, Any]: ...
    @abstractmethod
    async def minimize_window(self, window_id: int) -> Dict[str, Any]: ...
    @abstractmethod
    async def maximize_window(self, window_id: int) -> Dict[str, Any]: ...
    @abstractmethod
    async def restore_window(self, window_id: int) -> Dict[str, Any]: ...
    @abstractmethod
    async def close_window(self, window_id: int) -> Dict[str, Any]: ...

    @abstractmethod
    async def list_processes(self) -> Dict[str, Any]: ...
    @abstractmethod
    async def kill_process(self, pid: int) -> Dict[str, Any]: ...

    @abstractmethod
    async def registry_read(self, key_path: str, value_name: str = "") -> Dict[str, Any]: ...
    @abstractmethod
    async def registry_write(self, key_path: str, value_name: str, value: str, reg_type: str = "REG_SZ") -> Dict[str, Any]: ...

    @abstractmethod
    async def service_status(self, name: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def service_start(self, name: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def service_stop(self, name: str) -> Dict[str, Any]: ...


class BaseAccessibilityHandler(ABC):
    """Accessibility tree and element search."""

    @abstractmethod
    async def get_accessibility_tree(self) -> Dict[str, Any]: ...
    @abstractmethod
    async def find_element(self, role=None, title=None) -> Dict[str, Any]: ...


class BaseFileHandler(ABC):
    """File system operations — read, write, list, delete, move, copy."""

    @abstractmethod
    async def read_text(self, path: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def write_text(self, path: str, content: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def read_bytes(self, path: str, offset: int = 0, length: Optional[int] = None) -> Dict[str, Any]: ...
    @abstractmethod
    async def write_bytes(self, path: str, content: bytes) -> Dict[str, Any]: ...
    @abstractmethod
    async def file_exists(self, path: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def directory_exists(self, path: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def list_dir(self, path: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def create_dir(self, path: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def delete_file(self, path: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def delete_dir(self, path: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def get_file_size(self, path: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def move_file(self, src: str, dst: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def copy_file(self, src: str, dst: str) -> Dict[str, Any]: ...
